Adding state function to multiwalker
Farama-Foundation/PettingZoo pull request #1149
Opened 2023-12-22 15:46 UTC by ffelten

# Description

I added a state method giving a global view of the env on multiwalker

Realtes to #323 

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have run `pytest -v` and no errors are present.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-12-22 19:16 UTC, elliottower commented
Awesome, have seen that issue up for a while thanks for the contribution Florian

2023-12-22 19:18 UTC, elliottower commented on pettingzoo/sisl/multiwalker/multiwalker.py
> +        self.state_space = spaces.Box(
My only question is should this code be under multi walker base? The other two spaces are, but maybe it’s not possible

2023-12-22 19:20 UTC, elliottower commented on pettingzoo/sisl/multiwalker/multiwalker.py
> +        global_state = np.concatenate((all_walker_obs, package_obs)).astype(np.float32)
Makes sense to me at least, the two things that define the state are the package and the different walkers observations

2023-12-22 19:21 UTC, elliottower approved these changes

2023-12-22 19:25 UTC, jjshoots requested changes
LGTM. But yeah I would honestly put this into the base env since `multiwalker.py`'s file structure basically mirrors other sisl environment's file structure.

2023-12-22 21:47 UTC, ffelten commented
> LGTM. But yeah I would honestly put this into the base env since `multiwalker.py`'s file structure basically mirrors other sisl environment's file structure, it's already calling `self.env.x` so moving it into the base env makes more sense too.

@jjshoots done

2023-12-23 10:37 UTC, jjshoots approved these changes

2023-12-23 17:32 UTC, elliottower commented
Looks good to me as well, cheers (and happy holidays)

2023-12-23 17:32 UTC, merged