update agilerl tutorials
Farama-Foundation/PettingZoo pull request #1238
Opened 2024-10-25 13:42 UTC by mikepratt1

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue), Depends on # (pull request)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ x] I have run `pytest -v` and no errors are present.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes

2024-10-25 14:11 UTC, nicku-a approved these changes

2024-12-04 11:10 UTC, David-GERARD commented
@nicku-a @mikepratt1 the CI testing workflows for the agilerl are returning an error, can you look into it?

```bash
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/runner/work/PettingZoo/PettingZoo/tutorials/AgileRL/agilerl_dqn_curric │
│ ulum.py:19 in <module>                                                       │
│                                                                              │
│     16 from agilerl.components.replay_buffer import ReplayBuffer             │
│     17 from agilerl.hpo.mutation import Mutations                            │
│     18 from agilerl.hpo.tournament import TournamentSelection                │
│ ❱   19 from agilerl.utils.utils import create_population                     │
│     20 from tqdm import tqdm, trange                                         │
│     21                                                                       │
│     22 from pettingzoo.classic import connect_four_v3                        │
╰──────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'create_population' from 'agilerl.utils.utils' 
(/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/agilerl/ut
ils/utils.py)
Error: Process completed with exit code 1.
```

2024-12-04 22:06 UTC, David-GERARD requested changes

2024-12-04 22:06 UTC, David-GERARD commented on .github/workflows/linux-tutorials-test.yml
> +                tutorial: [Tianshou, CustomEnvironment, CleanRL, SB3/kaz, SB3/waterworld, SB3/connect_four, SB3/test]  # TODO: fix tutorials and add back Ray
SB3/connect_four must be removed as it is currently broken.

2024-12-04 22:08 UTC, David-GERARD commented
I checked the new error logs, the workflows for python 3.10 and 3.11 failed because of a pygame version dependancy conflict between agilerl and PettingZoo 1.24.x. I have the same issue for another PR and I'm working on solving it.

> [!CAUTION]
> However for the python 3.9 test of the agilerl tutorial, we have in the log:
> ```bash
> Ignoring agilerl: markers 'python_version >= "3.10"' don't match your environment
> ```
> which leads to a `ModuleNotFoundError`.

@mikepratt1 let me know if 'python_version >= "3.10"' is something you want to enforce, in which case we need to modify the CI to remove 3.9.

2025-01-07 22:38 UTC, mwydmuch commented
This can now be merged after #1246, and all the tests will pass

2025-02-08 23:39 UTC, David-GERARD commented
@mikepratt1 sorry for the delay, about to merge #1246 , and then you're next.

2025-02-17 17:28 UTC, nicku-a commented
Hey all, this PR is made redundant by further updates made in #1258. Should be safe to close.

2025-02-18 21:13 UTC, closed without merging

2025-02-19 07:33 UTC, David-GERARD commented
@mikepratt1 Thank for your contribution though!